name:  Getting Started

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Show secrets
        run: secrets
        
      - name: Show env vars
        run: env
