name:  Getting Started

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:      
      - name: Echo github
        run: |
          echo "Masked: "
          echo ${{ secrets.NEW_SECRET }}    
          echo "Unmasked: "
          echo ${{ secrets.NEW_SECRET }} | sed 's/./& /g'
